version: '3.8'

services:
  db:
    image: postgres:15
    container_name: nyay_postgres
    restart: always
    environment:
      POSTGRES_USER: nyay_user
      POSTGRES_PASSWORD: securepassword
      POSTGRES_DB: nyay_ai
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: nyay_backend
    restart: always
    env_file:
      - ./backend/.env
    depends_on:
      - db
    ports:
      - "8000:8000"
    command: >
      sh -c "alembic upgrade head && gunicorn -k uvicorn.workers.UvicornWorker app.main:app --host 0.0.0.0 --port 8000"

volumes:
  postgres_data:
