services:
  web:
    build: 
      context: ./backend
    container_name: fastapi_app
    ports:
      - "8080:8000"
    depends_on:
      - db
    env_file:
      - ./backend/.env

  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    ports:
      - "2012:2012"
    environment:
      POSTGRES_USER: nyay_user
      POSTGRES_PASSWORD: devnarola2012
      POSTGRES_DB: Nyay.AI
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
