name: Backend CI

on:
  push:
    paths:
      - 'backend/**'
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: nyay_user
          POSTGRES_PASSWORD: devnarola2012
          POSTGRES_DB: Nyay.AI
        ports:
          - 2012:2012
        options: >-
          --health-cmd="pg_isready"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        cd backend
        pip install -r requirements.txt

    - name: Run Tests
      run: |
        cd backend
        pytest
      env:
        DATABASE_URL: postgresql+psycopg2://nyay_user:devnarola2012@db:2012/Nyay.AI