name: FastAPI CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: nyay_user
          POSTGRES_PASSWORD: devnarola2012
          POSTGRES_DB: Nyay.AI
        ports:
          - 2012:2012
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        pip install -r backend/requirements.txt

    - name: Run Tests (if any)
      run: echo "✅ No tests yet"

    - name: Build Docker image
      run: docker build -t fastapi-app ./backend

    - name: Install Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/download/v2.24.5/docker-compose-linux-x86_64" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose
        docker-compose --version

    - name: Run Docker Compose
      run: docker-compose -f ./backend/docker-compose.yml up -d --build
